// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTickerCategory = `-- name: AddTickerCategory :exec
INSERT INTO ticker_categories (title)
VALUES ($1)
RETURNING id, title
`

func (q *Queries) AddTickerCategory(ctx context.Context, title pgtype.Text) error {
	_, err := q.db.Exec(ctx, addTickerCategory, title)
	return err
}

const addTickerMessage = `-- name: AddTickerMessage :exec
INSERT INTO ticker_messages (start_at,
                             end_at,
                             category_id,
                             info)
VALUES ($1, $2, $3, $4)
`

type AddTickerMessageParams struct {
	StartAt    pgtype.Timestamptz
	EndAt      pgtype.Timestamptz
	CategoryID pgtype.Int4
	Info       pgtype.Text
}

func (q *Queries) AddTickerMessage(ctx context.Context, arg AddTickerMessageParams) error {
	_, err := q.db.Exec(ctx, addTickerMessage,
		arg.StartAt,
		arg.EndAt,
		arg.CategoryID,
		arg.Info,
	)
	return err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (membership_number,
                     first_name, 
                     last_name,
                     email,
                     phone,
                     is_bowling_member,
                     is_life_member,
                     is_financial,
                     is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING membership_number, first_name, last_name, email, phone, is_bowling_member, is_life_member, is_financial, is_active, created_at, updated_at
`

type CreateMemberParams struct {
	MembershipNumber int32
	FirstName        string
	LastName         string
	Email            pgtype.Text
	Phone            pgtype.Text
	IsBowlingMember  pgtype.Bool
	IsLifeMember     pgtype.Bool
	IsFinancial      pgtype.Bool
	IsActive         pgtype.Bool
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.MembershipNumber,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.IsBowlingMember,
		arg.IsLifeMember,
		arg.IsFinancial,
		arg.IsActive,
	)
	var i Member
	err := row.Scan(
		&i.MembershipNumber,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.IsBowlingMember,
		&i.IsLifeMember,
		&i.IsFinancial,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateMember = `-- name: DeactivateMember :exec
UPDATE members
SET is_active = FALSE
WHERE membership_number = $1
`

func (q *Queries) DeactivateMember(ctx context.Context, membershipNumber int32) error {
	_, err := q.db.Exec(ctx, deactivateMember, membershipNumber)
	return err
}

const findActiveFinancialBowlingMembers = `-- name: FindActiveFinancialBowlingMembers :many
SELECT membership_number, first_name, last_name, email, phone, is_bowling_member, is_life_member, is_financial, is_active, created_at, updated_at FROM members
WHERE is_bowling_member = TRUE AND is_active = TRUE AND is_financial = TRUE
ORDER BY last_name, first_name
`

func (q *Queries) FindActiveFinancialBowlingMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.Query(ctx, findActiveFinancialBowlingMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.MembershipNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.IsBowlingMember,
			&i.IsLifeMember,
			&i.IsFinancial,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findActiveFinancialMembers = `-- name: FindActiveFinancialMembers :many
SELECT membership_number, first_name, last_name, email, phone, is_bowling_member, is_life_member, is_financial, is_active, created_at, updated_at FROM members
WHERE is_active = TRUE AND is_financial = TRUE
ORDER BY last_name, first_name
`

func (q *Queries) FindActiveFinancialMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.Query(ctx, findActiveFinancialMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.MembershipNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.IsBowlingMember,
			&i.IsLifeMember,
			&i.IsFinancial,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findActiveFinancialMembersByName = `-- name: FindActiveFinancialMembersByName :many
SELECT membership_number, first_name, last_name, email, phone, is_bowling_member, is_life_member, is_financial, is_active, created_at, updated_at FROM members
WHERE (first_name ILIKE '%' || $1 || '%' OR last_name ILIKE '%' || $1 || '%')
AND is_active = TRUE AND is_financial = TRUE
ORDER BY last_name, first_name
`

func (q *Queries) FindActiveFinancialMembersByName(ctx context.Context, dollar_1 pgtype.Text) ([]Member, error) {
	rows, err := q.db.Query(ctx, findActiveFinancialMembersByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.MembershipNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.IsBowlingMember,
			&i.IsLifeMember,
			&i.IsFinancial,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findActiveMembersByName = `-- name: FindActiveMembersByName :many
SELECT membership_number, first_name, last_name, email, phone, is_bowling_member, is_life_member, is_financial, is_active, created_at, updated_at FROM members
WHERE (first_name ILIKE '%' || $1 || '%' OR last_name ILIKE '%' || $1 || '%')
AND is_active = TRUE
ORDER BY last_name, first_name
`

func (q *Queries) FindActiveMembersByName(ctx context.Context, dollar_1 pgtype.Text) ([]Member, error) {
	rows, err := q.db.Query(ctx, findActiveMembersByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.MembershipNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.IsBowlingMember,
			&i.IsLifeMember,
			&i.IsFinancial,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findActiveTickers = `-- name: FindActiveTickers :many
SELECT m.start_at AS start_at,
       m.end_at AS end_at,
       c.title AS category,
       m.info AS info
FROM ticker_messages m
INNER JOIN ticker_categories c ON m.category_id = c.id
WHERE m.start_at <= now() AND m.end_at > now()
ORDER BY m.start_at
`

type FindActiveTickersRow struct {
	StartAt  pgtype.Timestamptz
	EndAt    pgtype.Timestamptz
	Category pgtype.Text
	Info     pgtype.Text
}

func (q *Queries) FindActiveTickers(ctx context.Context) ([]FindActiveTickersRow, error) {
	rows, err := q.db.Query(ctx, findActiveTickers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindActiveTickersRow
	for rows.Next() {
		var i FindActiveTickersRow
		if err := rows.Scan(
			&i.StartAt,
			&i.EndAt,
			&i.Category,
			&i.Info,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findInactiveMembers = `-- name: FindInactiveMembers :many
SELECT membership_number, first_name, last_name, email, phone, is_bowling_member, is_life_member, is_financial, is_active, created_at, updated_at FROM members
WHERE is_active = FALSE
ORDER BY last_name, first_name
`

func (q *Queries) FindInactiveMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.Query(ctx, findInactiveMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.MembershipNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.IsBowlingMember,
			&i.IsLifeMember,
			&i.IsFinancial,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLifeMembers = `-- name: FindLifeMembers :many
SELECT membership_number, first_name, last_name, email, phone, is_bowling_member, is_life_member, is_financial, is_active, created_at, updated_at FROM members
WHERE is_life_member = TRUE AND is_active = TRUE
ORDER BY last_name, first_name
`

func (q *Queries) FindLifeMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.Query(ctx, findLifeMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.MembershipNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.IsBowlingMember,
			&i.IsLifeMember,
			&i.IsFinancial,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMemberById = `-- name: FindMemberById :one
SELECT membership_number, first_name, last_name, email, phone, is_bowling_member, is_life_member, is_financial, is_active, created_at, updated_at FROM members
WHERE membership_number = $1 AND is_active = TRUE
`

func (q *Queries) FindMemberById(ctx context.Context, membershipNumber int32) (Member, error) {
	row := q.db.QueryRow(ctx, findMemberById, membershipNumber)
	var i Member
	err := row.Scan(
		&i.MembershipNumber,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.IsBowlingMember,
		&i.IsLifeMember,
		&i.IsFinancial,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findMembers = `-- name: FindMembers :many
SELECT membership_number, first_name, last_name, email, phone, is_bowling_member, is_life_member, is_financial, is_active, created_at, updated_at FROM members
ORDER BY last_name, first_name
`

func (q *Queries) FindMembers(ctx context.Context) ([]Member, error) {
	rows, err := q.db.Query(ctx, findMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.MembershipNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.IsBowlingMember,
			&i.IsLifeMember,
			&i.IsFinancial,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMembersByName = `-- name: FindMembersByName :many
SELECT membership_number, first_name, last_name, email, phone, is_bowling_member, is_life_member, is_financial, is_active, created_at, updated_at FROM members
WHERE (first_name ILIKE '%' || $1 || '%' OR last_name ILIKE '%' || $1 || '%')
ORDER BY last_name, first_name
`

func (q *Queries) FindMembersByName(ctx context.Context, dollar_1 pgtype.Text) ([]Member, error) {
	rows, err := q.db.Query(ctx, findMembersByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.MembershipNumber,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.IsBowlingMember,
			&i.IsLifeMember,
			&i.IsFinancial,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reactivateMember = `-- name: ReactivateMember :exec
UPDATE members
SET is_active = TRUE
WHERE membership_number = $1
`

func (q *Queries) ReactivateMember(ctx context.Context, membershipNumber int32) error {
	_, err := q.db.Exec(ctx, reactivateMember, membershipNumber)
	return err
}

const updateMemberDetails = `-- name: UpdateMemberDetails :exec
UPDATE members
SET first_name = $2,
    last_name = $3,
    email = $4,
    phone = $5,
    is_bowling_member = $6,
    is_life_member = $7,
    is_financial = $8,
    is_active = $9,
    updated_at = CURRENT_TIMESTAMP
WHERE membership_number = $1
`

type UpdateMemberDetailsParams struct {
	MembershipNumber int32
	FirstName        string
	LastName         string
	Email            pgtype.Text
	Phone            pgtype.Text
	IsBowlingMember  pgtype.Bool
	IsLifeMember     pgtype.Bool
	IsFinancial      pgtype.Bool
	IsActive         pgtype.Bool
}

func (q *Queries) UpdateMemberDetails(ctx context.Context, arg UpdateMemberDetailsParams) error {
	_, err := q.db.Exec(ctx, updateMemberDetails,
		arg.MembershipNumber,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.IsBowlingMember,
		arg.IsLifeMember,
		arg.IsFinancial,
		arg.IsActive,
	)
	return err
}
