// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Member struct {
	MembershipNumber int32
	FirstName        string
	LastName         string
	Email            pgtype.Text
	Phone            pgtype.Text
	IsBowlingMember  pgtype.Bool
	IsLifeMember     pgtype.Bool
	IsActive         pgtype.Bool
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}
