// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Competition struct {
	ID             int32
	StartYear      int32
	Division       string
	BowlslinkID    pgtype.Text
	BowlersPerTeam int32
	TeamsPerSide   int32
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type Member struct {
	MembershipNumber int32
	FirstName        string
	LastName         string
	Email            pgtype.Text
	Phone            pgtype.Text
	IsBowlingMember  pgtype.Bool
	IsLifeMember     pgtype.Bool
	IsActive         pgtype.Bool
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type Round struct {
	ID                int32
	CompetitionID     pgtype.Int4
	RoundNumber       int32
	DutySelector      int32
	Umpire            pgtype.Int4
	PlayedAt          pgtype.Timestamptz
	Venue             string
	Opponent          string
	IsPlayedOnSurface pgtype.Bool
	Surface           string
	LowRinkNumber     pgtype.Int4
	HighRinkNumber    pgtype.Int4
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
}

type Side struct {
	ID            int32
	CompetitionID pgtype.Int4
	Team1ID       pgtype.Int4
	Team2ID       pgtype.Int4
	Team3ID       pgtype.Int4
	Team4ID       pgtype.Int4
	Points        int32
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type Team struct {
	ID           int32
	RoundID      pgtype.Int4
	TeamNumber   int32
	Duty         pgtype.Text
	RoleLead     int32
	RoleSecond   pgtype.Int4
	RoleThird    pgtype.Int4
	RoleSkip     int32
	ShotsFor     pgtype.Int4
	ShotsAgainst pgtype.Int4
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
